### PR TITLE
Bugfix/make ecs metadata work

### PR DESCRIPTION
**Pull request by grrizzly**
Hello,

I work internally with @austinmcorso and am also attempting to use this client in ECS.

This is a follow-up to #12 and addresses #13 . The other PR wasn't quite ready to go. Additionally, we found a way of passively detecting / retrieving the requisite information from the ECS metadata endpoint.

Let me know if I can answer any questions, and thanks for taking a look!

### CODE REVIEW

**Comment by tyrsius** [comment]
Is this one ready to go?

**Comment by grrizzly** [comment]
@tyrsius Is there any way you could publish a `beta` before merging? 

I basically copied this repo into the app where it's being used to test it out. Would be great to try a published version to make extra sure everything's working as intended.

**Comment by tyrsius** [comment]
@grrizzly done.

`npm i cerberus-node-client@beta`
or
`npm i cerberus-node-client@1.5.1-beta.1`

**Comment by grrizzly** [comment]
Confirmed to work with beta publish, clear to merge!

**Comment by tyrsius** [comment]
@grrizzly this has been published. The beta tag will be unpublished on thursday, make sure you update the build that was using it

**Pull request merged**
