### PR TITLE
Use Cerberus '/v2/auth/iam-principal'

### PR DESCRIPTION
**Pull request by sdford**

### CODE REVIEW

**Comment by tyrsius** [comment]
@sdford Are you available to beta test this if I release it under a beta version?

**Comment by sdford** [comment]
@tyrsius I tested the changes on an EC2 instance and also ran the spec tests locally.

Is there other testing you have in mind?

**Comment by tyrsius** [comment]
@sdford I published this under `cerberus-node-client@1.3.0-beta.1`. I'll install it on a lambda and notify the slack channel it exists.

If you could update the CHANGELOG I would appreciate it

**Comment by sdford** [comment]
@tyrsius Sounds good.

Done.

**Pull request merged**
